name: main

on:
  push:
    paths:
      - '**'
      - '!.github/workflows/cross.yml'
      - '!.github/workflows/ow-libc.yml'
      - '!tools/*'
#  pull_request:
#    paths:
#     - '**'
#     - '!.github/workflows/cross.yml'
#     - '!.github/workflows/ow-libc.yml'
#     - '!tools/*'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: setup
        run: 'sudo apt-get install texinfo libncurses5-dev libelf-dev ncompress'

      - name: checkout
        uses: actions/checkout@v2

      - name: cache
        id: cache
        uses: actions/cache@v4
        with:
          path: cross
          key: cross-${{ hashFiles('tools/*') }}-${{ runner.os }}

      - name: prepare
        if: steps.cache.outputs.cache-hit != 'true'
        run: 'mkdir -p cross'

      - name: cross
        if: steps.cache.outputs.cache-hit != 'true'
        run: tools/build.sh

      - name: build
        run: ./build.sh auto allimages

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: rom.wsc
          path: image/rom.wsc
